-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 21:30:11 2024
-- Model: Modelo docweb    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema docweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema docweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `docweb` DEFAULT CHARACTER SET utf8 ;
USE `docweb` ;

-- -----------------------------------------------------
-- Table `docweb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docweb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `docweb`.`usuarios` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `login` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `rol` SET("admin", "repoadmin", "user") NOT NULL DEFAULT 'user',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `docweb`.`repositorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docweb`.`repositorios` ;

CREATE TABLE IF NOT EXISTS `docweb`.`repositorios` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NULL,
  `ruta` VARCHAR(256) NOT NULL,
  `login` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(128) NOT NULL,
  `tipo` SET("ficheros", "docuware", "smb", "otros") NOT NULL DEFAULT 'otros',
  `ID_Admin` INT UNSIGNED NOT NULL,
  `extraData` BLOB NULL COMMENT 'Datos extra que se puedan almacenar del repositorio.',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `docweb`.`identificadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docweb`.`identificadores` ;

CREATE TABLE IF NOT EXISTS `docweb`.`identificadores` (
  `ID_Usuario` INT UNSIGNED NOT NULL,
  `clave` VARCHAR(256) NOT NULL,
  `valor` VARCHAR(256) NOT NULL,
  `ID_Repositorio` INT UNSIGNED NOT NULL,
  INDEX `fk_identificadores_usuarios_idx` (`ID_Usuario` ASC) VISIBLE,
  INDEX `fk_identificadores_repositorio_idx` (`ID_Repositorio` ASC) VISIBLE,
  CONSTRAINT `fk_identificadores_usuarios`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `docweb`.`usuarios` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_identificadores_repositorio`
    FOREIGN KEY (`ID_Repositorio`)
    REFERENCES `docweb`.`repositorios` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `docweb`.`campos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docweb`.`campos` ;

CREATE TABLE IF NOT EXISTS `docweb`.`campos` (
  `ID_Repositorio` INT UNSIGNED NOT NULL,
  `campo` VARCHAR(256) NOT NULL,
  INDEX `fk_campos_repositorio_idx` (`ID_Repositorio` ASC) VISIBLE,
  CONSTRAINT `fk_campos_repositorio`
    FOREIGN KEY (`ID_Repositorio`)
    REFERENCES `docweb`.`repositorios` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
