-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 18:58:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webdoc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webdoc` ;

-- -----------------------------------------------------
-- Schema webdoc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webdoc` DEFAULT CHARACTER SET utf8 ;
USE `webdoc` ;

-- -----------------------------------------------------
-- Table `webdoc`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webdoc`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `webdoc`.`usuarios` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `login` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `rol` SET("admin", "repoadmin", "user") NOT NULL DEFAULT 'user',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webdoc`.`repositorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webdoc`.`repositorios` ;

CREATE TABLE IF NOT EXISTS `webdoc`.`repositorios` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NULL,
  `ruta` VARCHAR(256) NOT NULL,
  `login` VARCHAR(128) NULL,
  `pass` VARCHAR(128) NULL,
  `tipo` SET("ficheros", "docuware", "smb", "otros") NOT NULL DEFAULT 'otros',
  `ID_Admin` INT UNSIGNED NOT NULL,
  `extraData` BLOB NULL COMMENT 'Datos extra que se puedan almacenar del repositorio.',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webdoc`.`identificadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webdoc`.`identificadores` ;

CREATE TABLE IF NOT EXISTS `webdoc`.`identificadores` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_Usuario` INT UNSIGNED NOT NULL,
  `clave` VARCHAR(256) NOT NULL,
  `valor` VARCHAR(256) NOT NULL,
  `ID_Repositorio` INT UNSIGNED NOT NULL,
  INDEX `fk_identificadores_usuarios_idx` (`ID_Usuario` ASC) VISIBLE,
  INDEX `fk_identificadores_repositorio_idx` (`ID_Repositorio` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_identificadores_usuarios`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `webdoc`.`usuarios` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_identificadores_repositorio`
    FOREIGN KEY (`ID_Repositorio`)
    REFERENCES `webdoc`.`repositorios` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webdoc`.`codigosRecuperaPass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webdoc`.`codigosRecuperaPass` ;

CREATE TABLE IF NOT EXISTS `webdoc`.`codigosRecuperaPass` (
  `codigoRecuperacion` VARCHAR(256) NOT NULL,
  `usuario_ID` INT UNSIGNED NOT NULL,
  `tiempo` DATETIME NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`codigoRecuperacion`, `usuario_ID`),
  UNIQUE INDEX `codigoRecupera_UNIQUE` (`codigoRecuperacion` ASC) VISIBLE,
  INDEX `fk_codigosRecuperaPass_usuarios1_idx` (`usuario_ID` ASC) VISIBLE,
  UNIQUE INDEX `usuarios_ID_UNIQUE` (`usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_codigosRecuperaPass_usuarios1`
    FOREIGN KEY (`usuario_ID`)
    REFERENCES `webdoc`.`usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
